name: Code Check

on:
  workflow_call:

jobs:
  code_quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v2.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Check formatting
        run: deno fmt --check
      - name: Check Lint
        run: deno lint
      - name: Type check
        run: deno check mod.ts
