name: Unit Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v2.x]
    steps:
      - uses: actions/checkout@v4
      - name: Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Run all tests
        run: deno test -A ./tests -q

